{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goidp.secretname" . }}
  {{- if .Values.postgresql.primary.persistence.enabled }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
type: kubernetes.io/generic
data:
{{- ( include "goidp.gensecret" . ) | indent 2 -}}
{{- end }}
